# Generated by Django 4.1.3 on 2022-12-28 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sessoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('sessao_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100)),
                ('author', models.CharField(default='Autor', max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('sinopse', models.TextField()),
                ('image', models.ImageField(upload_to='books/')),
                ('presented_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sessaoid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.sessoes')),
            ],
        ),
    ]
