# Generated by Django 4.1.3 on 2022-12-10 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sessoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('sessao_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('sinopse', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='books/')),
                ('sessaoid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.sessoes')),
            ],
        ),
    ]
