# Generated by Django 4.1.3 on 2022-12-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_books_sinopse'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='author',
            field=models.CharField(default='Autor', max_length=50),
        ),
        migrations.AddField(
            model_name='books',
            name='presented_by',
            field=models.CharField(default='Autor', max_length=50),
        ),
    ]
